spring:
  mail:
    host: smtp.163.com
    username: 17573402104@qq.com
    password: KEZANFQTFNWNFMHE
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
  security:
    jwt:
      key: abcdefghi
    filter:
      order: -100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
  data:
    redis:
      host: localhost
      port: 6379

