spring:
  mail:
    host: smtp.163.com
    username: 17573402104@163.com
    password: KEZANFQTFNWNFMHE
  rabbitmq:
    addresses: 192.168.42.111
    username: admin
    password: admin
    virtual-host: /
    port: 5672
  security:
    jwt:
      key: abcdefghi
    filter:
      order: -100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
  data:
    redis:
      host: localhost
      port: 6379
  web:
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  minio:
    endpoint: 'http://192.168.42.111:9000'
    username: 'minio'
    password: 'password'
  weather:
    key: a91c85d8ec8d4fefb6af6de7c2d4b76d
server:
  port: 8000