spring:
  security:
    jwt:
      key: abcdefghi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
  data:
    redis:
      host: localhost
      port: 6379

